### ISSUE TITLE
breakpoint on untitled document

### ISSUE THREAD

**Issue by GustavoAntero** [kirksl/karate-runner#160]
Hello guys,

we found an issue while doing debug in karate runner.

### Issue
karate runner should not send breakpoints with non existent paths to the debug server.

### Steps to reproduce

* open a folder with a karate project with vscode
* open a new untitled document
* select language mode for karate
* write some steps
* place a breakpoint
* save to file disk
* start debug session with karate runner

### Logs:

```
*  Executing task: java -cp karate.jar com.intuit.karate.Main -d
12:28:02.556 [main]  INFO  com.intuit.karate - Karate version: 1.2.0
12:28:04.870 [main]  INFO  com.intuit.karate.debug.DapServer - debug server started on port: 53334
12:28:05.668 [nioEventLoopGroup-3-1]  DEBUG c.i.karate.debug.DapServerHandler - command line: c:\documentos-karate\Flujo alumno\Flujoalum.feature:3
java.nio.file.InvalidPathException: Illegal char <:> at index 8: untitled:Untitled-1
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at com.intuit.karate.debug.DapServerHandler.normalizePath(DapServerHandler.java:127)
```

**Comment by kirksl** [comment]
@GustavoAntero wondering if this still an issue for you and if you have found a workaround.  Also curious how big of a problem is this.  We haven't heard received any feedback from other users experiencing this issue.  Thank you.

**Comment by kirksl** [comment]
Closing due to inactivity.
We will leave this on our backlog and reopen if this issue persists.
